### ISSUE TITLE
Please add the sensitivity feature

### ISSUE THREAD

**Issue by ars4l4n** [colxi/pull-to-refresh-chrome-extension#1]
I have to scroll up around 8 times with my logitech G502 for the page to be refreshed.
It would be great if you added the sensitivity feature.

Perhaps, your extension works well with mice that can give you a long continuous scroll with a lot of scroll steps but mine just does a few steps and then interrupts which resets some of the scroll steps you did so you're required to do more in order to reach the threshhold for refreshing.

**Comment by proohit** [comment]
I'm currently working on a way to be able to adjust the sensitivity.. Am facing some troubles at the moment but after I'm done I will make a pull request...

**Comment by ars4l4n** [comment]
nice to hear that

________________________________
Von: Direnc Timur <notifications@github.com>
Gesendet: Samstag, 2. November 2019 11:04
An: colxi/pull-to-refresh-chrome-extension <pull-to-refresh-chrome-extension@noreply.github.com>
Cc: ars4l4n <arsalan.mazari@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [colxi/pull-to-refresh-chrome-extension] Please add the sensitivity feature (#1)


I'm currently working on a way to be able to adjust the sensitivity.. Am facing some troubles at the moment but after I'm done I will make a pull request...

**Comment by proohit** [comment]
I don't know when or if he is going to merge the changes but you can manually clone and load my fork with the settings if you want.
https://github.com/proohit/pull-to-refresh-chrome-extension/tree/add_sensitivity_options?files=1
Just go into it, git clone it into a folder, then go into Chrome, open Chrome extensions page, remove the old version of pull to refresh and click on "load unpacked". Select the newly cloned folder and you should be able to select "options" from within the extensions page or from the icon in the upper bar.
For you, the "mouse" setting is important. Set it to like 13 and try it out.

**Comment by colxi** [comment]
I'll review and merge the changes today if everything looks good. Thanks
for the improvement

**Comment by colxi** [comment]
Changes have been merged. Some additional improvements have been applied too, and Chrome Extension submitted to Chrome Store. Is pending review, and new version (v1.0.8) should be available in the following days.
